// Sermon.java
package com.RunDMCPP.Backend.models;
import java.util.Objects;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "sermon")
public class Sermon {

    private String id;
    private String name;
    private String description;
    private String youtubeLink;
    private String dateTime;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName = "description")
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute(attributeName = "youtubeLink")
    public String getYoutubeLink() {
        return youtubeLink;
    }
    public void setYoutubeLink(String youtubeLink) {
        this.youtubeLink = youtubeLink;
    }

    @DynamoDBAttribute(attributeName = "dateTime")
    public String getDateTime() {
        return dateTime;
    }
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o){
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Sermon sermon = (Sermon) o;
        return Objects.equals(this.id, sermon.id) && Objects.equals(this.name, sermon.name) && Objects.equals(this.description, sermon.description) && Objects.equals(this.youtubeLink, sermon.youtubeLink) && Objects.equals(this.dateTime, sermon.dateTime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.id, this.name, this.description, this.youtubeLink, this.dateTime);
    }
}
